import { address } from './address.js';
import { permissionsDocs } from './permissions.js';
import natspec from './natspec';

// setup the mainnet addresses md file
// returns several maps of state for the natspec to add smart links
const { artifacts, artifactsCategoryMap, artifactImplMap, artifactDependencyMap } = address(); 

// set up the permissions file
permissionsDocs();

// set up the natspec autogenerated contract documentation
natspec(artifacts, artifactsCategoryMap, artifactImplMap, artifactDependencyMap);